inputs:
  resources:
    workload_resource_sync_enabled: true
  cbpf:
    af_packet:
      interface_regex: "^(tap.*|cali.*|veth.*|eth.*|en[osipx].*|lxc.*|lo|[0-9a-f]+_h|docker[0-9]*|br-.*)$"
processors:
  request_log:
    application_protocol_inference:
      enabled_protocols:
        - HTTP
        - HTTP2
        - gRPC
        - FastCGI
        - MySQL
        - PostgreSQL
        - Redis
        - MongoDB
        - Memcached
        - Kafka
        - AMQP
        - DNS
        - TLS
    filters:
      tag_filters:
        HTTP:
          - field_name: request_resource 
            operator: equal
            value: /api/v1/telegraf
        HTTP2:
          - field_name: request_resource
            operator: equal
            value: /agent.Synchronizer/GenesisSync
          - field_name: request_resource
            operator: equal
            value: /agent.Synchronizer/Push
          - field_name: request_resource
            operator: equal
            value: /agent.Synchronizer/Sync
global:
  circuit_breakers:
    relative_sys_load:
      trigger_threshold: 0