inputs:
  resources:
    workload_resource_sync_enabled: true
  cbpf:
    af_packet:
      interface_regex: "^(tap.*|cali.*|veth.*|eth.*|en[osipx].*|lxc.*|lo|[0-9a-f]+_h|docker[0-9]*|br-.*)$"
processors:
  request_log:
    application_protocol_inference:
      enabled_protocols:
        - HTTP
        - HTTP2
        - gRPC
        - FastCGI
        - MySQL
        - PostgreSQL
        - Redis
        - MongoDB
        - Memcached
        - Kafka
        - AMQP
        - DNS
        - TLS
global:
  circuit_breakers:
    relative_sys_load:
      trigger_threshold: 0